"""New Product entity

Revision ID: 1cbe8d72826b
Revises: b1ab70c68b0f
Create Date: 2020-07-22 18:32:01.859074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cbe8d72826b'
down_revision = 'b1ab70c68b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PIZZA', 'DRINK', name='producttype'), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('size', sa.Enum('LARGE', 'MEDIUM', 'SMALL', name='productsize'), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=64), nullable=True),
    sa.Column('base', sa.Enum('WHITE', 'RED', name='pizzabase'), nullable=True),
    sa.Column('crust', sa.Enum('WHITE', 'RED', name='pizzabase'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
