"""User infor in Order

Revision ID: 3af5ee694618
Revises: e1b5f98b4995
Create Date: 2020-07-23 17:06:25.607489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af5ee694618'
down_revision = 'e1b5f98b4995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('order', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'username')
    op.drop_column('order', 'phone')
    op.drop_column('order', 'address')
    # ### end Alembic commands ###
