"""Order status

Revision ID: 8773c59669d0
Revises: 3af5ee694618
Create Date: 2020-07-23 18:19:19.331592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8773c59669d0'
down_revision = '3af5ee694618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Enum('ORDERED', 'CONFIRMED', 'READY', 'DELIVERED', name='orderstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
