"""Users timestamps

Revision ID: d7d78fc8c876
Revises: f2f72c9d43bc
Create Date: 2020-07-21 16:46:20.102462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d78fc8c876'
down_revision = 'f2f72c9d43bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_password_expires_timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('register_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_register_timestamp'), 'user', ['register_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_register_timestamp'), table_name='user')
    op.drop_column('user', 'register_timestamp')
    op.drop_column('user', 'last_password_expires_timestamp')
    # ### end Alembic commands ###
