"""Order and ProductOrder connection

Revision ID: e1b5f98b4995
Revises: 4ae65443010a
Create Date: 2020-07-23 15:41:50.202554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b5f98b4995'
down_revision = '4ae65443010a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_order', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_order', type_='foreignkey')
    op.drop_column('product_order', 'order_id')
    # ### end Alembic commands ###
